// Generated by CoffeeScript 1.6.2
(function() {
  var API, Client;

  Client = require("./client").Client;

  API = require("./api").API;

  require("./api/sources");

  require("./api/operators");

  require("./api/outputs");

  require("./api/encoders");

  module.exports = {
    Client: Client,
    API: API
  };

}).call(this);
