// Generated by CoffeeScript 1.4.0
(function() {
  var API,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  API = require("../api").API;

  API.Output = {};

  API.Output.Ao = (function(_super) {

    __extends(Ao, _super);

    function Ao() {
      return Ao.__super__.constructor.apply(this, arguments);
    }

    Ao.path = "/output/ao";

    return Ao;

  })(API.Private.Stateful);

  API.Output.Dummy = (function(_super) {

    __extends(Dummy, _super);

    function Dummy() {
      return Dummy.__super__.constructor.apply(this, arguments);
    }

    Dummy.path = "/output/dummy";

    return Dummy;

  })(API.Private.Stateful);

  API.Output.IcecastBase = (function(_super) {

    __extends(IcecastBase, _super);

    function IcecastBase() {
      return IcecastBase.__super__.constructor.apply(this, arguments);
    }

    IcecastBase.path = "/output/icecast";

    return IcecastBase;

  })(API.Private.Stateful);

  API.Output.Icecast = function(options) {
    var object;
    if (options == null) {
      options = {};
    }
    object = API.Output.IcecastBase;
    object.path = "/output/icecast.mp3.128";
    return object;
  };

}).call(this);
