// Generated by CoffeeScript 1.6.2
(function() {
  var API, _ref, _ref1, _ref2, _ref3, _ref4,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  API = require("../api").API;

  API.Blank = (function(_super) {
    __extends(Blank, _super);

    function Blank() {
      _ref = Blank.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Blank.path = "/blank";

    return Blank;

  })(API.Private.Source);

  API.Single = (function(_super) {
    __extends(Single, _super);

    function Single() {
      _ref1 = Single.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Single.path = "/single";

    return Single;

  })(API.Private.Source);

  API.Request = {};

  API.Request.Queue = (function(_super) {
    __extends(Queue, _super);

    function Queue() {
      this.push = __bind(this.push, this);      _ref2 = Queue.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    Queue.path = "/request/queue";

    Queue.prototype.push = function(requests, fn) {
      var options;

      if (!(requests instanceof Array)) {
        requests = [requests];
      }
      options = {
        method: "PUT",
        path: "/sources/" + this.name + "/requests",
        query: requests
      };
      return this.http_request(options, fn);
    };

    return Queue;

  })(API.Private.Source);

  API.Request.Dynamic = (function(_super) {
    __extends(Dynamic, _super);

    function Dynamic() {
      _ref3 = Dynamic.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    Dynamic.path = "/request/dynamic";

    return Dynamic;

  })(API.Private.Source);

  API.Input = {};

  API.Input.Http = (function(_super) {
    __extends(Http, _super);

    function Http() {
      _ref4 = Http.__super__.constructor.apply(this, arguments);
      return _ref4;
    }

    Http.path = "/input/http";

    return Http;

  })(API.Private.Stateful);

}).call(this);
